/**
 * Copyright (C) 2015 - present McLeod Moores Software Limited.  All rights reserved.
 *
 * Please see distribution for license.
 */
package com.opengamma.engine.marketdata.spec;

import java.util.Map;
import java.util.NoSuchElementException;

import org.joda.beans.ImmutableBean;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

/**
 * A market data specification for a source that will always state that market data is available, even if this is not the case.
 */
@BeanDefinition(hierarchy = "immutable")
public class AlwaysAvailableMarketDataSpecification implements MarketDataSpecification, ImmutableBean {
  /** Serialization version */
  private static final long serialVersionUID = 1L;

  //------------------------- AUTOGENERATED START -------------------------
  /**
   * The meta-bean for {@code AlwaysAvailableMarketDataSpecification}.
   * @return the meta-bean, not null
   */
  public static AlwaysAvailableMarketDataSpecification.Meta meta() {
    return AlwaysAvailableMarketDataSpecification.Meta.INSTANCE;
  }

  static {
    MetaBean.register(AlwaysAvailableMarketDataSpecification.Meta.INSTANCE);
  }

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static AlwaysAvailableMarketDataSpecification.Builder builder() {
    return new AlwaysAvailableMarketDataSpecification.Builder();
  }

  /**
   * Restricted constructor.
   * @param builder  the builder to copy from, not null
   */
  protected AlwaysAvailableMarketDataSpecification(AlwaysAvailableMarketDataSpecification.Builder builder) {
  }

  @Override
  public AlwaysAvailableMarketDataSpecification.Meta metaBean() {
    return AlwaysAvailableMarketDataSpecification.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      return true;
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(32);
    buf.append("AlwaysAvailableMarketDataSpecification{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  protected void toString(StringBuilder buf) {
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code AlwaysAvailableMarketDataSpecification}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null);

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    public AlwaysAvailableMarketDataSpecification.Builder builder() {
      return new AlwaysAvailableMarketDataSpecification.Builder();
    }

    @Override
    public Class<? extends AlwaysAvailableMarketDataSpecification> beanType() {
      return AlwaysAvailableMarketDataSpecification.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code AlwaysAvailableMarketDataSpecification}.
   */
  public static class Builder extends DirectFieldsBeanBuilder<AlwaysAvailableMarketDataSpecification> {

    /**
     * Restricted constructor.
     */
    protected Builder() {
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      throw new NoSuchElementException("Unknown property: " + propertyName);
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      throw new NoSuchElementException("Unknown property: " + propertyName);
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public AlwaysAvailableMarketDataSpecification build() {
      return new AlwaysAvailableMarketDataSpecification(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(32);
      buf.append("AlwaysAvailableMarketDataSpecification.Builder{");
      int len = buf.length();
      toString(buf);
      if (buf.length() > len) {
        buf.setLength(buf.length() - 2);
      }
      buf.append('}');
      return buf.toString();
    }

    protected void toString(StringBuilder buf) {
    }

  }

  //-------------------------- AUTOGENERATED END --------------------------
}
