/**
 * Copyright (C) 2009 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.masterdb.spring;

import java.util.Map;

import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.core.change.JmsChangeManager;
import com.opengamma.masterdb.holiday.DbHolidayMaster;
import org.joda.beans.MetaBean;
import org.joda.beans.gen.BeanDefinition;

/**
 * Spring factory bean to create the database holiday master.
 */
@BeanDefinition
public class DbHolidayMasterFactoryBean extends AbstractDbMasterFactoryBean<DbHolidayMaster> {

  /**
   * Creates an instance.
   */
  public DbHolidayMasterFactoryBean() {
    super(DbHolidayMaster.class);
  }

  //-------------------------------------------------------------------------
  @Override
  public DbHolidayMaster createObject() {
    final DbHolidayMaster master = new DbHolidayMaster(getDbConnector());
    if (getUniqueIdScheme() != null) {
      master.setUniqueIdScheme(getUniqueIdScheme());
    }
    if (getMaxRetries() != null) {
      master.setMaxRetries(getMaxRetries());
    }
    if (getJmsConnector() != null) {
      final JmsChangeManager cm = new JmsChangeManager(getJmsConnector().ensureTopicName(getJmsChangeManagerTopic()));
      master.setChangeManager(cm);
      cm.start();
    }
    return master;
  }

  //------------------------- AUTOGENERATED START -------------------------
  /**
   * The meta-bean for {@code DbHolidayMasterFactoryBean}.
   * @return the meta-bean, not null
   */
  public static DbHolidayMasterFactoryBean.Meta meta() {
    return DbHolidayMasterFactoryBean.Meta.INSTANCE;
  }

  static {
    MetaBean.register(DbHolidayMasterFactoryBean.Meta.INSTANCE);
  }

  @Override
  public DbHolidayMasterFactoryBean.Meta metaBean() {
    return DbHolidayMasterFactoryBean.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  @Override
  public DbHolidayMasterFactoryBean clone() {
    return JodaBeanUtils.cloneAlways(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      return super.equals(obj);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = 7;
    return hash ^ super.hashCode();
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(32);
    buf.append("DbHolidayMasterFactoryBean{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  @Override
  protected void toString(StringBuilder buf) {
    super.toString(buf);
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code DbHolidayMasterFactoryBean}.
   */
  public static class Meta extends AbstractDbMasterFactoryBean.Meta<DbHolidayMaster> {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, (DirectMetaPropertyMap) super.metaPropertyMap());

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    public BeanBuilder<? extends DbHolidayMasterFactoryBean> builder() {
      return new DirectBeanBuilder<>(new DbHolidayMasterFactoryBean());
    }

    @Override
    public Class<? extends DbHolidayMasterFactoryBean> beanType() {
      return DbHolidayMasterFactoryBean.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
  }

  //-------------------------- AUTOGENERATED END --------------------------
}
