/**
 * Copyright (C) 2015-Present McLeod Moores Software Limited.  All rights reserved.
 */
package com.mcleodmoores.quandl.component;

import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.mcleodmoores.quandl.function.QuandlCurveFunctions;
import com.mcleodmoores.quandl.function.QuandlFunctionConfiguration;
import com.mcleodmoores.quandl.function.QuandlFunctions;
import com.opengamma.component.factory.source.FunctionConfigurationSourceComponentFactory;
import com.opengamma.engine.function.config.FunctionConfigurationSource;

/**
 * A factory that initializes all functions in this project and populates the repository.
 */
@BeanDefinition
public class QuandlFunctionConfigurationSourceComponentFactory extends FunctionConfigurationSourceComponentFactory {

  @Override
  protected FunctionConfigurationSource standardConfiguration() {
    return QuandlFunctionConfiguration.instance();
  }

  @Override
  protected FunctionConfigurationSource curveConfigurations() {
    return QuandlCurveFunctions.providers(getConfigMaster());
  }

  @Override
  protected List<FunctionConfigurationSource> initSources() {
    final List<FunctionConfigurationSource> sources = new LinkedList<>(super.initSources());
    sources.add(QuandlFunctions.instance());
    return sources;
  }
  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code QuandlFunctionConfigurationSourceComponentFactory}.
   * @return the meta-bean, not null
   */
  public static QuandlFunctionConfigurationSourceComponentFactory.Meta meta() {
    return QuandlFunctionConfigurationSourceComponentFactory.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(QuandlFunctionConfigurationSourceComponentFactory.Meta.INSTANCE);
  }

  @Override
  public QuandlFunctionConfigurationSourceComponentFactory.Meta metaBean() {
    return QuandlFunctionConfigurationSourceComponentFactory.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  @Override
  public QuandlFunctionConfigurationSourceComponentFactory clone() {
    return JodaBeanUtils.cloneAlways(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      return super.equals(obj);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = 7;
    return hash ^ super.hashCode();
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(32);
    buf.append("QuandlFunctionConfigurationSourceComponentFactory{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  @Override
  protected void toString(StringBuilder buf) {
    super.toString(buf);
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code QuandlFunctionConfigurationSourceComponentFactory}.
   */
  public static class Meta extends FunctionConfigurationSourceComponentFactory.Meta {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, (DirectMetaPropertyMap) super.metaPropertyMap());

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    public BeanBuilder<? extends QuandlFunctionConfigurationSourceComponentFactory> builder() {
      return new DirectBeanBuilder<QuandlFunctionConfigurationSourceComponentFactory>(new QuandlFunctionConfigurationSourceComponentFactory());
    }

    @Override
    public Class<? extends QuandlFunctionConfigurationSourceComponentFactory> beanType() {
      return QuandlFunctionConfigurationSourceComponentFactory.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
