/**
 * Copyright (C) 2009 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.master.trade;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;

import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.OpenGammaRuntimeException;
import com.opengamma.id.VersionCorrection;
import com.opengamma.master.AbstractSearchResult;
import com.opengamma.util.PublicSPI;

/**
 * Result from searching for Trades.
 * <p>
 * The returned documents will match the search criteria.
 * See {@link TradeSearchRequest} for more details.
 */
@PublicSPI
@BeanDefinition
public class TradeSearchResult extends AbstractSearchResult<TradeDocument> {

  /**
   * Creates an instance.
   */
  public TradeSearchResult() {
  }

  /**
   * Creates an instance from a collection of documents.
   *
   * @param coll  the collection of documents to add, not null
   */
  public TradeSearchResult(final Collection<TradeDocument> coll) {
    super(coll);
  }

  /**
   * Creates an instance specifying the version-correction searched for.
   *
   * @param versionCorrection  the version-correction of the data, not null
   */
  public TradeSearchResult(final VersionCorrection versionCorrection) {
    setVersionCorrection(versionCorrection);
  }

  //-------------------------------------------------------------------------
  /**
   * Gets the returned Trades from within the documents.
   *
   * @return the Trades, not null
   */
  public List<ManageableTrade> getTrades() {
    final List<ManageableTrade> result = new ArrayList<>();
    if (getDocuments() != null) {
      for (final TradeDocument doc : getDocuments()) {
        result.add(doc.getTrade());
      }
    }
    return result;
  }

  /**
   * Gets the first Trade, or null if no documents.
   *
   * @return the first Trade, null if none
   */
  public ManageableTrade getFirstTrade() {
    return getDocuments().size() > 0 ? getDocuments().get(0).getTrade() : null;
  }

  /**
   * Gets the single result expected from a query.
   * <p>
   * This throws an exception if more than 1 result is actually available.
   * Thus, this method implies an assumption about uniqueness of the queried Trade.
   *
   * @return the matching Trade, not null
   * @throws IllegalStateException if no Trade was found
   */
  public ManageableTrade getSingleTrade() {
    if (getDocuments().size() != 1) {
      throw new OpenGammaRuntimeException("Expecting single resulting match, and was " + getDocuments().size());
    }
    return getDocuments().get(0).getTrade();
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code TradeSearchResult}.
   * @return the meta-bean, not null
   */
  public static Meta meta() {
    return Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(Meta.INSTANCE);
  }

  @Override
  public Meta metaBean() {
    return Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  @Override
  public TradeSearchResult clone() {
    return JodaBeanUtils.cloneAlways(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      return super.equals(obj);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = 7;
    return hash ^ super.hashCode();
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(32);
    buf.append("TradeSearchResult{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  @Override
  protected void toString(StringBuilder buf) {
    super.toString(buf);
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code TradeSearchResult}.
   */
  public static class Meta extends AbstractSearchResult.Meta<TradeDocument> {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, (DirectMetaPropertyMap) super.metaPropertyMap());

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    public BeanBuilder<? extends TradeSearchResult> builder() {
      return new DirectBeanBuilder<TradeSearchResult>(new TradeSearchResult());
    }

    @Override
    public Class<? extends TradeSearchResult> beanType() {
      return TradeSearchResult.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
