/**
 * Copyright (C) 2012 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 *
 * Modified by McLeod Moores Software Limited.
 *
 * Copyright (C) 2015-Present McLeod Moores Software Limited.  All rights reserved.
 */
package com.mcleodmoores.integration.simulatedexamples.component;

import java.util.Collection;
import java.util.Map;

import net.sf.ehcache.CacheManager;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.springframework.core.io.Resource;

import com.google.common.collect.ImmutableList;
import com.mcleodmoores.integration.simulatedexamples.data.NormalizationRules;
import com.mcleodmoores.integration.simulatedexamples.data.SyntheticIdResolver;
import com.mcleodmoores.integration.simulatedexamples.data.TestJmsTopicNameResolver;
import com.mcleodmoores.integration.simulatedexamples.data.TestLiveDataServer;
import com.mcleodmoores.integration.simulatedexamples.data.TestLiveDataServerMBean;
import com.opengamma.component.ComponentRepository;
import com.opengamma.component.factory.livedata.AbstractStandardLiveDataServerComponentFactory;
import com.opengamma.core.id.ExternalSchemes;
import com.opengamma.livedata.normalization.NormalizationRuleSet;
import com.opengamma.livedata.normalization.StandardRuleResolver;
import com.opengamma.livedata.normalization.StandardRules;
import com.opengamma.livedata.resolver.DefaultDistributionSpecificationResolver;
import com.opengamma.livedata.server.StandardLiveDataServer;
import com.opengamma.livedata.server.distribution.JmsSenderFactory;
import com.opengamma.provider.livedata.LiveDataMetaData;
import com.opengamma.provider.livedata.LiveDataServerTypes;

/**
 * Component factory for producing simulated live data. Adapted from the factory in the simulated examples package.
 */
@BeanDefinition
public class TestLiveDataServerComponentFactory extends AbstractStandardLiveDataServerComponentFactory {
  /**
   * The JMS connector.
   */
  @PropertyDefinition(validate = "notNull")
  private Resource _simulatedData;
  /**
   * The EH cache configuration.
   */
  @PropertyDefinition(validate = "notNull")
  private CacheManager _cacheManager;
  /**
   * Maximum millis between ticks
   */
  @PropertyDefinition
  private Integer _maxMillisBetweenTicks = TestLiveDataServer.MAX_MILLIS_BETWEEN_TICKS;
  /**
   * Scaling factor
   */
  @PropertyDefinition
  private Double _scalingFactor = TestLiveDataServer.SCALING_FACTOR;

  //-------------------------------------------------------------------------
  @Override
  protected StandardLiveDataServer initServer(final ComponentRepository repo) {
    final TestLiveDataServer server = new TestLiveDataServer(getCacheManager(), getSimulatedData(), getScalingFactor(), getMaxMillisBetweenTicks());

    final Collection<NormalizationRuleSet> rules = ImmutableList.of(StandardRules.getNoNormalization(), NormalizationRules.getMarketValueNormalization());
    final DefaultDistributionSpecificationResolver distSpecResolver = new DefaultDistributionSpecificationResolver(
        new SyntheticIdResolver(),
        new StandardRuleResolver(rules),
        new TestJmsTopicNameResolver());
    server.setDistributionSpecificationResolver(distSpecResolver);

    final JmsSenderFactory senderFactory = new JmsSenderFactory(getJmsConnector());
    server.setMarketDataSenderFactory(senderFactory);

    repo.registerMBean(new TestLiveDataServerMBean(server));
    return server;
  }

  @Override
  protected LiveDataMetaData createMetaData(final ComponentRepository repo) {
    return new LiveDataMetaData(ImmutableList.of(ExternalSchemes.OG_SYNTHETIC_TICKER), LiveDataServerTypes.STANDARD, TestMarketDataComponentFactory.SIMULATED_LIVE_SOURCE_NAME);
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code TestLiveDataServerComponentFactory}.
   * @return the meta-bean, not null
   */
  public static TestLiveDataServerComponentFactory.Meta meta() {
    return TestLiveDataServerComponentFactory.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(TestLiveDataServerComponentFactory.Meta.INSTANCE);
  }

  @Override
  public TestLiveDataServerComponentFactory.Meta metaBean() {
    return TestLiveDataServerComponentFactory.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the JMS connector.
   * @return the value of the property, not null
   */
  public Resource getSimulatedData() {
    return _simulatedData;
  }

  /**
   * Sets the JMS connector.
   * @param simulatedData  the new value of the property, not null
   */
  public void setSimulatedData(Resource simulatedData) {
    JodaBeanUtils.notNull(simulatedData, "simulatedData");
    this._simulatedData = simulatedData;
  }

  /**
   * Gets the the {@code simulatedData} property.
   * @return the property, not null
   */
  public final Property<Resource> simulatedData() {
    return metaBean().simulatedData().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the EH cache configuration.
   * @return the value of the property, not null
   */
  public CacheManager getCacheManager() {
    return _cacheManager;
  }

  /**
   * Sets the EH cache configuration.
   * @param cacheManager  the new value of the property, not null
   */
  public void setCacheManager(CacheManager cacheManager) {
    JodaBeanUtils.notNull(cacheManager, "cacheManager");
    this._cacheManager = cacheManager;
  }

  /**
   * Gets the the {@code cacheManager} property.
   * @return the property, not null
   */
  public final Property<CacheManager> cacheManager() {
    return metaBean().cacheManager().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets maximum millis between ticks
   * @return the value of the property
   */
  public Integer getMaxMillisBetweenTicks() {
    return _maxMillisBetweenTicks;
  }

  /**
   * Sets maximum millis between ticks
   * @param maxMillisBetweenTicks  the new value of the property
   */
  public void setMaxMillisBetweenTicks(Integer maxMillisBetweenTicks) {
    this._maxMillisBetweenTicks = maxMillisBetweenTicks;
  }

  /**
   * Gets the the {@code maxMillisBetweenTicks} property.
   * @return the property, not null
   */
  public final Property<Integer> maxMillisBetweenTicks() {
    return metaBean().maxMillisBetweenTicks().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets scaling factor
   * @return the value of the property
   */
  public Double getScalingFactor() {
    return _scalingFactor;
  }

  /**
   * Sets scaling factor
   * @param scalingFactor  the new value of the property
   */
  public void setScalingFactor(Double scalingFactor) {
    this._scalingFactor = scalingFactor;
  }

  /**
   * Gets the the {@code scalingFactor} property.
   * @return the property, not null
   */
  public final Property<Double> scalingFactor() {
    return metaBean().scalingFactor().createProperty(this);
  }

  //-----------------------------------------------------------------------
  @Override
  public TestLiveDataServerComponentFactory clone() {
    return JodaBeanUtils.cloneAlways(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      TestLiveDataServerComponentFactory other = (TestLiveDataServerComponentFactory) obj;
      return JodaBeanUtils.equal(getSimulatedData(), other.getSimulatedData()) &&
          JodaBeanUtils.equal(getCacheManager(), other.getCacheManager()) &&
          JodaBeanUtils.equal(getMaxMillisBetweenTicks(), other.getMaxMillisBetweenTicks()) &&
          JodaBeanUtils.equal(getScalingFactor(), other.getScalingFactor()) &&
          super.equals(obj);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = 7;
    hash = hash * 31 + JodaBeanUtils.hashCode(getSimulatedData());
    hash = hash * 31 + JodaBeanUtils.hashCode(getCacheManager());
    hash = hash * 31 + JodaBeanUtils.hashCode(getMaxMillisBetweenTicks());
    hash = hash * 31 + JodaBeanUtils.hashCode(getScalingFactor());
    return hash ^ super.hashCode();
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(160);
    buf.append("TestLiveDataServerComponentFactory{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  @Override
  protected void toString(StringBuilder buf) {
    super.toString(buf);
    buf.append("simulatedData").append('=').append(JodaBeanUtils.toString(getSimulatedData())).append(',').append(' ');
    buf.append("cacheManager").append('=').append(JodaBeanUtils.toString(getCacheManager())).append(',').append(' ');
    buf.append("maxMillisBetweenTicks").append('=').append(JodaBeanUtils.toString(getMaxMillisBetweenTicks())).append(',').append(' ');
    buf.append("scalingFactor").append('=').append(JodaBeanUtils.toString(getScalingFactor())).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code TestLiveDataServerComponentFactory}.
   */
  public static class Meta extends AbstractStandardLiveDataServerComponentFactory.Meta {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code simulatedData} property.
     */
    private final MetaProperty<Resource> _simulatedData = DirectMetaProperty.ofReadWrite(
        this, "simulatedData", TestLiveDataServerComponentFactory.class, Resource.class);
    /**
     * The meta-property for the {@code cacheManager} property.
     */
    private final MetaProperty<CacheManager> _cacheManager = DirectMetaProperty.ofReadWrite(
        this, "cacheManager", TestLiveDataServerComponentFactory.class, CacheManager.class);
    /**
     * The meta-property for the {@code maxMillisBetweenTicks} property.
     */
    private final MetaProperty<Integer> _maxMillisBetweenTicks = DirectMetaProperty.ofReadWrite(
        this, "maxMillisBetweenTicks", TestLiveDataServerComponentFactory.class, Integer.class);
    /**
     * The meta-property for the {@code scalingFactor} property.
     */
    private final MetaProperty<Double> _scalingFactor = DirectMetaProperty.ofReadWrite(
        this, "scalingFactor", TestLiveDataServerComponentFactory.class, Double.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, (DirectMetaPropertyMap) super.metaPropertyMap(),
        "simulatedData",
        "cacheManager",
        "maxMillisBetweenTicks",
        "scalingFactor");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -349682038:  // simulatedData
          return _simulatedData;
        case -1452875317:  // cacheManager
          return _cacheManager;
        case -1944334024:  // maxMillisBetweenTicks
          return _maxMillisBetweenTicks;
        case -794828874:  // scalingFactor
          return _scalingFactor;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BeanBuilder<? extends TestLiveDataServerComponentFactory> builder() {
      return new DirectBeanBuilder<TestLiveDataServerComponentFactory>(new TestLiveDataServerComponentFactory());
    }

    @Override
    public Class<? extends TestLiveDataServerComponentFactory> beanType() {
      return TestLiveDataServerComponentFactory.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code simulatedData} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Resource> simulatedData() {
      return _simulatedData;
    }

    /**
     * The meta-property for the {@code cacheManager} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<CacheManager> cacheManager() {
      return _cacheManager;
    }

    /**
     * The meta-property for the {@code maxMillisBetweenTicks} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Integer> maxMillisBetweenTicks() {
      return _maxMillisBetweenTicks;
    }

    /**
     * The meta-property for the {@code scalingFactor} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Double> scalingFactor() {
      return _scalingFactor;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -349682038:  // simulatedData
          return ((TestLiveDataServerComponentFactory) bean).getSimulatedData();
        case -1452875317:  // cacheManager
          return ((TestLiveDataServerComponentFactory) bean).getCacheManager();
        case -1944334024:  // maxMillisBetweenTicks
          return ((TestLiveDataServerComponentFactory) bean).getMaxMillisBetweenTicks();
        case -794828874:  // scalingFactor
          return ((TestLiveDataServerComponentFactory) bean).getScalingFactor();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -349682038:  // simulatedData
          ((TestLiveDataServerComponentFactory) bean).setSimulatedData((Resource) newValue);
          return;
        case -1452875317:  // cacheManager
          ((TestLiveDataServerComponentFactory) bean).setCacheManager((CacheManager) newValue);
          return;
        case -1944334024:  // maxMillisBetweenTicks
          ((TestLiveDataServerComponentFactory) bean).setMaxMillisBetweenTicks((Integer) newValue);
          return;
        case -794828874:  // scalingFactor
          ((TestLiveDataServerComponentFactory) bean).setScalingFactor((Double) newValue);
          return;
      }
      super.propertySet(bean, propertyName, newValue, quiet);
    }

    @Override
    protected void validate(Bean bean) {
      JodaBeanUtils.notNull(((TestLiveDataServerComponentFactory) bean)._simulatedData, "simulatedData");
      JodaBeanUtils.notNull(((TestLiveDataServerComponentFactory) bean)._cacheManager, "cacheManager");
      super.validate(bean);
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
