/**
 * Copyright (C) 2017 - present McLeod Moores Software Limited.  All rights reserved.
 */
package com.mcleodmoores.examples.simulated.component;

import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.mcleodmoores.examples.simulated.function.ExamplesSimulatedFunctionConfiguration;
import com.mcleodmoores.financial.function.curve.functions.CurveFunctions;
import com.opengamma.component.factory.source.FunctionConfigurationSourceComponentFactory;
import com.opengamma.engine.function.config.CombiningFunctionConfigurationSource;
import com.opengamma.engine.function.config.FunctionConfigurationSource;
import org.joda.beans.MetaBean;
import org.joda.beans.gen.BeanDefinition;

/**
 *
 */
@BeanDefinition
public class ExampleFunctionConfigurationSourceComponentFactory extends FunctionConfigurationSourceComponentFactory {

  @Override
  protected FunctionConfigurationSource standardConfiguration() {
    return ExamplesSimulatedFunctionConfiguration.instance(getConfigMaster());
  }

  @Override
  protected List<FunctionConfigurationSource> curveAndSurfaceSources() {
    final List<FunctionConfigurationSource> sources = new LinkedList<>();
    sources.add(curveParameterConfigurations());
    sources.add(fxForwardCurveConfigurations());
    sources.add(timeSeriesConfigurations());
    sources.add(surfaceConfigConfigurations());
    return sources;
  }

  @Override
  protected FunctionConfigurationSource curveConfigurations() {
    final ExamplesSimulatedFunctionConfiguration functionsConfig = new ExamplesSimulatedFunctionConfiguration(getConfigMaster());
    return CombiningFunctionConfigurationSource.of(CurveFunctions.providers(getConfigMaster(), functionsConfig.getCurveInfo()));
  }

  @Override
  protected List<FunctionConfigurationSource> initSources() {
    return super.initSources();
  }

  //------------------------- AUTOGENERATED START -------------------------
  /**
   * The meta-bean for {@code ExampleFunctionConfigurationSourceComponentFactory}.
   * @return the meta-bean, not null
   */
  public static ExampleFunctionConfigurationSourceComponentFactory.Meta meta() {
    return ExampleFunctionConfigurationSourceComponentFactory.Meta.INSTANCE;
  }

  static {
    MetaBean.register(ExampleFunctionConfigurationSourceComponentFactory.Meta.INSTANCE);
  }

  @Override
  public ExampleFunctionConfigurationSourceComponentFactory.Meta metaBean() {
    return ExampleFunctionConfigurationSourceComponentFactory.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  @Override
  public ExampleFunctionConfigurationSourceComponentFactory clone() {
    return JodaBeanUtils.cloneAlways(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      return super.equals(obj);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = 7;
    return hash ^ super.hashCode();
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(32);
    buf.append("ExampleFunctionConfigurationSourceComponentFactory{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  @Override
  protected void toString(StringBuilder buf) {
    super.toString(buf);
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code ExampleFunctionConfigurationSourceComponentFactory}.
   */
  public static class Meta extends FunctionConfigurationSourceComponentFactory.Meta {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, (DirectMetaPropertyMap) super.metaPropertyMap());

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    public BeanBuilder<? extends ExampleFunctionConfigurationSourceComponentFactory> builder() {
      return new DirectBeanBuilder<>(new ExampleFunctionConfigurationSourceComponentFactory());
    }

    @Override
    public Class<? extends ExampleFunctionConfigurationSourceComponentFactory> beanType() {
      return ExampleFunctionConfigurationSourceComponentFactory.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
  }

  //-------------------------- AUTOGENERATED END --------------------------
}
