/**
 * Copyright (C) 2019 - present McLeod Moores Software Limited.  All rights reserved.
 */
package com.opengamma.financial.security;

import java.util.Map;

import org.apache.commons.lang.NotImplementedException;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.id.ExternalIdBundle;
import com.opengamma.id.UniqueId;

/**
 * For testing
 */
@BeanDefinition
class DummySecurity extends FinancialSecurity {
  private static final long serialVersionUID = 1L;

  /**
   *
   */
  private DummySecurity() {
    super("dummy");
  }

  /**
   * @param securityType
   *          the security type
   */
  DummySecurity(final String securityType) {
    super(securityType);
  }

  /**
   * @param uniqueId
   *          the unique id
   * @param name
   *          the name
   * @param securityType
   *          the security type
   * @param bundle
   *          the id bundle
   */
  DummySecurity(final UniqueId uniqueId, final String name, final String securityType, final ExternalIdBundle bundle) {
    super(uniqueId, name, securityType, bundle);
  }

  @Override
  public <T> T accept(final FinancialSecurityVisitor<T> visitor) {
    throw new NotImplementedException("dummy");
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code DummySecurity}.
   * @return the meta-bean, not null
   */
  public static DummySecurity.Meta meta() {
    return DummySecurity.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(DummySecurity.Meta.INSTANCE);
  }

  @Override
  public DummySecurity.Meta metaBean() {
    return DummySecurity.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  @Override
  public DummySecurity clone() {
    return JodaBeanUtils.cloneAlways(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      return super.equals(obj);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = 7;
    return hash ^ super.hashCode();
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(32);
    buf.append("DummySecurity{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  @Override
  protected void toString(StringBuilder buf) {
    super.toString(buf);
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code DummySecurity}.
   */
  static class Meta extends FinancialSecurity.Meta {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, (DirectMetaPropertyMap) super.metaPropertyMap());

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    public BeanBuilder<? extends DummySecurity> builder() {
      return new DirectBeanBuilder<DummySecurity>(new DummySecurity());
    }

    @Override
    public Class<? extends DummySecurity> beanType() {
      return DummySecurity.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
