/**
 * Copyright (C) 2019 - present McLeod Moores Software Limited.  All rights reserved.
 */
package com.mcleodmoores.financial.function.credit.configs;

import java.util.Map;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.analytics.financial.credit.creditdefaultswap.StandardCDSQuotingConvention;
import com.opengamma.core.config.Config;
import com.opengamma.core.config.ConfigGroups;
import com.opengamma.financial.analytics.curve.CurveDefinition;
import com.opengamma.financial.analytics.ircurve.strips.CurveNode;
import com.opengamma.id.ObjectId;
import com.opengamma.id.ObjectIdentifiable;
import com.opengamma.util.credit.CreditCurveIdentifier;

/**
 * A definition for a credit spread curve that contains the nodes and information about the type of the quote (e.g. quoted spread, points up-front).
 */
@BeanDefinition
@Config(description = "Credit curve definition", group = ConfigGroups.CURVES)
public class CreditCurveDefinition extends CurveDefinition implements ObjectIdentifiable {
  private static final long serialVersionUID = 1L;

  /**
   * The object identifier, which should be derived from a {@link CreditCurveIdentifier}.
   */
  @PropertyDefinition(validate = "notNull")
  private ObjectId _objectId;

  /**
   * The type of the quote.
   */
  @PropertyDefinition(validate = "notNull")
  private StandardCDSQuotingConvention _quoteConvention;

  /**
   * For the builder.
   */
  CreditCurveDefinition() {
    super();
  }

  /**
   * Constructs a definition.
   *
   * @param name
   *          the name of the definition, not null
   * @param creditCurveIdentifier
   *          the identifier of the curve, not null
   * @param nodes
   *          the curve nodes, not null
   * @param quoteConvention
   *          the convention of the quotes, not null
   */
  public CreditCurveDefinition(final String name, final CreditCurveIdentifier creditCurveIdentifier, final Set<CurveNode> nodes,
      final StandardCDSQuotingConvention quoteConvention) {
    super(name, nodes);
    setObjectId(creditCurveIdentifier.getObjectId());
    setQuoteConvention(quoteConvention);
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code CreditCurveDefinition}.
   * @return the meta-bean, not null
   */
  public static CreditCurveDefinition.Meta meta() {
    return CreditCurveDefinition.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(CreditCurveDefinition.Meta.INSTANCE);
  }

  @Override
  public CreditCurveDefinition.Meta metaBean() {
    return CreditCurveDefinition.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the object identifier, which should be derived from a {@link CreditCurveIdentifier}.
   * @return the value of the property, not null
   */
  public ObjectId getObjectId() {
    return _objectId;
  }

  /**
   * Sets the object identifier, which should be derived from a {@link CreditCurveIdentifier}.
   * @param objectId  the new value of the property, not null
   */
  public void setObjectId(ObjectId objectId) {
    JodaBeanUtils.notNull(objectId, "objectId");
    this._objectId = objectId;
  }

  /**
   * Gets the the {@code objectId} property.
   * @return the property, not null
   */
  public final Property<ObjectId> objectId() {
    return metaBean().objectId().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the type of the quote.
   * @return the value of the property, not null
   */
  public StandardCDSQuotingConvention getQuoteConvention() {
    return _quoteConvention;
  }

  /**
   * Sets the type of the quote.
   * @param quoteConvention  the new value of the property, not null
   */
  public void setQuoteConvention(StandardCDSQuotingConvention quoteConvention) {
    JodaBeanUtils.notNull(quoteConvention, "quoteConvention");
    this._quoteConvention = quoteConvention;
  }

  /**
   * Gets the the {@code quoteConvention} property.
   * @return the property, not null
   */
  public final Property<StandardCDSQuotingConvention> quoteConvention() {
    return metaBean().quoteConvention().createProperty(this);
  }

  //-----------------------------------------------------------------------
  @Override
  public CreditCurveDefinition clone() {
    return JodaBeanUtils.cloneAlways(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      CreditCurveDefinition other = (CreditCurveDefinition) obj;
      return JodaBeanUtils.equal(getObjectId(), other.getObjectId()) &&
          JodaBeanUtils.equal(getQuoteConvention(), other.getQuoteConvention()) &&
          super.equals(obj);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = 7;
    hash = hash * 31 + JodaBeanUtils.hashCode(getObjectId());
    hash = hash * 31 + JodaBeanUtils.hashCode(getQuoteConvention());
    return hash ^ super.hashCode();
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(96);
    buf.append("CreditCurveDefinition{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  @Override
  protected void toString(StringBuilder buf) {
    super.toString(buf);
    buf.append("objectId").append('=').append(JodaBeanUtils.toString(getObjectId())).append(',').append(' ');
    buf.append("quoteConvention").append('=').append(JodaBeanUtils.toString(getQuoteConvention())).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code CreditCurveDefinition}.
   */
  public static class Meta extends CurveDefinition.Meta {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code objectId} property.
     */
    private final MetaProperty<ObjectId> _objectId = DirectMetaProperty.ofReadWrite(
        this, "objectId", CreditCurveDefinition.class, ObjectId.class);
    /**
     * The meta-property for the {@code quoteConvention} property.
     */
    private final MetaProperty<StandardCDSQuotingConvention> _quoteConvention = DirectMetaProperty.ofReadWrite(
        this, "quoteConvention", CreditCurveDefinition.class, StandardCDSQuotingConvention.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, (DirectMetaPropertyMap) super.metaPropertyMap(),
        "objectId",
        "quoteConvention");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 90495162:  // objectId
          return _objectId;
        case 2049149709:  // quoteConvention
          return _quoteConvention;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BeanBuilder<? extends CreditCurveDefinition> builder() {
      return new DirectBeanBuilder<CreditCurveDefinition>(new CreditCurveDefinition());
    }

    @Override
    public Class<? extends CreditCurveDefinition> beanType() {
      return CreditCurveDefinition.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code objectId} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<ObjectId> objectId() {
      return _objectId;
    }

    /**
     * The meta-property for the {@code quoteConvention} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<StandardCDSQuotingConvention> quoteConvention() {
      return _quoteConvention;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 90495162:  // objectId
          return ((CreditCurveDefinition) bean).getObjectId();
        case 2049149709:  // quoteConvention
          return ((CreditCurveDefinition) bean).getQuoteConvention();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 90495162:  // objectId
          ((CreditCurveDefinition) bean).setObjectId((ObjectId) newValue);
          return;
        case 2049149709:  // quoteConvention
          ((CreditCurveDefinition) bean).setQuoteConvention((StandardCDSQuotingConvention) newValue);
          return;
      }
      super.propertySet(bean, propertyName, newValue, quiet);
    }

    @Override
    protected void validate(Bean bean) {
      JodaBeanUtils.notNull(((CreditCurveDefinition) bean)._objectId, "objectId");
      JodaBeanUtils.notNull(((CreditCurveDefinition) bean)._quoteConvention, "quoteConvention");
      super.validate(bean);
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
