/**
 * Copyright (C) 2019 - present McLeod Moores Software Limited.  All rights reserved.
 */
package com.mcleodmoores.financial.function.credit.configs;

import java.io.Serializable;
import java.util.Collection;
import java.util.Map;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBean;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.threeten.bp.LocalDate;

import com.opengamma.financial.analytics.ircurve.strips.CurveNodeWithIdentifier;
import com.opengamma.util.ArgumentChecker;
import com.opengamma.util.credit.CreditCurveIdentifier;

/**
 *
 */
@BeanDefinition
public class CreditCurveSpecification extends DirectBean implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * The nodes with identifiers.
   */
  @PropertyDefinition(validate = "notNull")
  private Collection<CurveNodeWithIdentifier> _nodes;

  /**
   * The identifier of the specification.
   */
  @PropertyDefinition(validate = "notNull")
  private CreditCurveIdentifier _id;

  /**
   * The curve date.
   */
  @PropertyDefinition(validate = "notNull")
  private LocalDate _curveDate;

  CreditCurveSpecification() {
  }

  public CreditCurveSpecification(final LocalDate curveDate, final CreditCurveIdentifier id, final Collection<CurveNodeWithIdentifier> nodes) {
    setCurveDate(curveDate);
    setId(id);
    setNodes(nodes);
  }

  public void addNode(final CurveNodeWithIdentifier node) {
    _nodes.add(ArgumentChecker.notNull(node, "node"));
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code CreditCurveSpecification}.
   * @return the meta-bean, not null
   */
  public static CreditCurveSpecification.Meta meta() {
    return CreditCurveSpecification.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(CreditCurveSpecification.Meta.INSTANCE);
  }

  @Override
  public CreditCurveSpecification.Meta metaBean() {
    return CreditCurveSpecification.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the nodes with identifiers.
   * @return the value of the property, not null
   */
  public Collection<CurveNodeWithIdentifier> getNodes() {
    return _nodes;
  }

  /**
   * Sets the nodes with identifiers.
   * @param nodes  the new value of the property, not null
   */
  public void setNodes(Collection<CurveNodeWithIdentifier> nodes) {
    JodaBeanUtils.notNull(nodes, "nodes");
    this._nodes = nodes;
  }

  /**
   * Gets the the {@code nodes} property.
   * @return the property, not null
   */
  public final Property<Collection<CurveNodeWithIdentifier>> nodes() {
    return metaBean().nodes().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the identifier of the specification.
   * @return the value of the property, not null
   */
  public CreditCurveIdentifier getId() {
    return _id;
  }

  /**
   * Sets the identifier of the specification.
   * @param id  the new value of the property, not null
   */
  public void setId(CreditCurveIdentifier id) {
    JodaBeanUtils.notNull(id, "id");
    this._id = id;
  }

  /**
   * Gets the the {@code id} property.
   * @return the property, not null
   */
  public final Property<CreditCurveIdentifier> id() {
    return metaBean().id().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the curve date.
   * @return the value of the property, not null
   */
  public LocalDate getCurveDate() {
    return _curveDate;
  }

  /**
   * Sets the curve date.
   * @param curveDate  the new value of the property, not null
   */
  public void setCurveDate(LocalDate curveDate) {
    JodaBeanUtils.notNull(curveDate, "curveDate");
    this._curveDate = curveDate;
  }

  /**
   * Gets the the {@code curveDate} property.
   * @return the property, not null
   */
  public final Property<LocalDate> curveDate() {
    return metaBean().curveDate().createProperty(this);
  }

  //-----------------------------------------------------------------------
  @Override
  public CreditCurveSpecification clone() {
    return JodaBeanUtils.cloneAlways(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      CreditCurveSpecification other = (CreditCurveSpecification) obj;
      return JodaBeanUtils.equal(getNodes(), other.getNodes()) &&
          JodaBeanUtils.equal(getId(), other.getId()) &&
          JodaBeanUtils.equal(getCurveDate(), other.getCurveDate());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(getNodes());
    hash = hash * 31 + JodaBeanUtils.hashCode(getId());
    hash = hash * 31 + JodaBeanUtils.hashCode(getCurveDate());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(128);
    buf.append("CreditCurveSpecification{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  protected void toString(StringBuilder buf) {
    buf.append("nodes").append('=').append(JodaBeanUtils.toString(getNodes())).append(',').append(' ');
    buf.append("id").append('=').append(JodaBeanUtils.toString(getId())).append(',').append(' ');
    buf.append("curveDate").append('=').append(JodaBeanUtils.toString(getCurveDate())).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code CreditCurveSpecification}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code nodes} property.
     */
    @SuppressWarnings({"unchecked", "rawtypes" })
    private final MetaProperty<Collection<CurveNodeWithIdentifier>> _nodes = DirectMetaProperty.ofReadWrite(
        this, "nodes", CreditCurveSpecification.class, (Class) Collection.class);
    /**
     * The meta-property for the {@code id} property.
     */
    private final MetaProperty<CreditCurveIdentifier> _id = DirectMetaProperty.ofReadWrite(
        this, "id", CreditCurveSpecification.class, CreditCurveIdentifier.class);
    /**
     * The meta-property for the {@code curveDate} property.
     */
    private final MetaProperty<LocalDate> _curveDate = DirectMetaProperty.ofReadWrite(
        this, "curveDate", CreditCurveSpecification.class, LocalDate.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "nodes",
        "id",
        "curveDate");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 104993457:  // nodes
          return _nodes;
        case 3355:  // id
          return _id;
        case 770856253:  // curveDate
          return _curveDate;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BeanBuilder<? extends CreditCurveSpecification> builder() {
      return new DirectBeanBuilder<CreditCurveSpecification>(new CreditCurveSpecification());
    }

    @Override
    public Class<? extends CreditCurveSpecification> beanType() {
      return CreditCurveSpecification.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code nodes} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Collection<CurveNodeWithIdentifier>> nodes() {
      return _nodes;
    }

    /**
     * The meta-property for the {@code id} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<CreditCurveIdentifier> id() {
      return _id;
    }

    /**
     * The meta-property for the {@code curveDate} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<LocalDate> curveDate() {
      return _curveDate;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 104993457:  // nodes
          return ((CreditCurveSpecification) bean).getNodes();
        case 3355:  // id
          return ((CreditCurveSpecification) bean).getId();
        case 770856253:  // curveDate
          return ((CreditCurveSpecification) bean).getCurveDate();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @SuppressWarnings("unchecked")
    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 104993457:  // nodes
          ((CreditCurveSpecification) bean).setNodes((Collection<CurveNodeWithIdentifier>) newValue);
          return;
        case 3355:  // id
          ((CreditCurveSpecification) bean).setId((CreditCurveIdentifier) newValue);
          return;
        case 770856253:  // curveDate
          ((CreditCurveSpecification) bean).setCurveDate((LocalDate) newValue);
          return;
      }
      super.propertySet(bean, propertyName, newValue, quiet);
    }

    @Override
    protected void validate(Bean bean) {
      JodaBeanUtils.notNull(((CreditCurveSpecification) bean)._nodes, "nodes");
      JodaBeanUtils.notNull(((CreditCurveSpecification) bean)._id, "id");
      JodaBeanUtils.notNull(((CreditCurveSpecification) bean)._curveDate, "curveDate");
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
